### ISSUE TITLE
Downloading some albums does not work.

### ISSUE THREAD

**Issue by talioto** [marekrei/smuploader#4]
The test upload and download worked, and one album was download fine, but all albums give the following error:

Traceback (most recent call last):
  File "/usr/local/bin/smdownloader", line 86, in <module>
    download_album(album_name = args.album, path = args.path, resume = args.resume, verbose = args.verbose)
  File "/usr/local/bin/smdownloader", line 38, in download_album
    images = smugmug.get_album_images(album_id)
  File "/Library/Python/2.7/site-packages/smuploader/smugmug.py", line 182, in get_album_images
    images.append({"ImageKey": image['ImageKey'], "Uri": image["Uri"], "FileName": image["FileName"], "ArchivedMD5": image["ArchivedMD5"], "OriginalSize": image["OriginalSize"]})
KeyError: 'OriginalSize'

**Comment by talioto** [comment]
It seem that using pip install ... didn't install the latest code. I manually edited a couple of lines with respect to OriginalSize and that seemed to fix the problem. I'm not great with Python -- what's the best way to install the latest code?

**Comment by marekrei** [comment]
Updated readme to give instructions on how to install locally, from the git repository.
